// Demo data for frontend-only mode
// Lovable faqat frontend ishga tushiradi, shuning uchun demo mode doimiy yoqilgan

export const DEMO_USER = {
  id: 'demo-user-1',
  username: 'demo',
  email: 'demo@sellercloudx.com',
  firstName: 'Demo',
  lastName: 'Hamkor',
  role: 'partner' as const,
  isActive: true,
};

export const DEMO_ADMIN = {
  id: 'admin-1',
  username: 'admin',
  email: 'admin@sellercloudx.com',
  firstName: 'Admin',
  lastName: 'Manager',
  role: 'admin' as const,
  isActive: true,
};

export const DEMO_PARTNER = {
  id: 'demo-partner-1',
  userId: 'demo-user-1',
  businessName: 'TechShop UZ',
  businessCategory: 'Elektronika',
  pricingTier: 'professional',
  isApproved: true,
  monthlyRevenue: '150000000',
  commissionRate: '3.5',
  telegramConnected: true,
  marketplaces: ['Uzum', 'Wildberries', 'Ozon'],
  aiEnabled: true,
  createdAt: new Date('2024-01-15').toISOString(),
};

export const DEMO_PARTNERS_LIST = [
  { ...DEMO_PARTNER },
  {
    id: 'partner-2',
    userId: 'user-2',
    businessName: 'Fashion Style',
    businessCategory: 'Kiyim-kechak',
    pricingTier: 'starter_pro',
    isApproved: true,
    monthlyRevenue: '85000000',
    commissionRate: '4',
    telegramConnected: true,
    marketplaces: ['Uzum', 'Wildberries'],
    aiEnabled: true,
    createdAt: new Date('2024-02-20').toISOString(),
  },
  {
    id: 'partner-3',
    userId: 'user-3',
    businessName: 'Home Comfort',
    businessCategory: 'Uy-ro\'zg\'or',
    pricingTier: 'basic',
    isApproved: true,
    monthlyRevenue: '42000000',
    commissionRate: '5',
    telegramConnected: false,
    marketplaces: ['Uzum'],
    aiEnabled: false,
    createdAt: new Date('2024-03-10').toISOString(),
  },
  {
    id: 'partner-4',
    userId: 'user-4',
    businessName: 'Sport Pro',
    businessCategory: 'Sport',
    pricingTier: 'free_starter',
    isApproved: false,
    monthlyRevenue: '0',
    commissionRate: '6',
    telegramConnected: false,
    marketplaces: [],
    aiEnabled: false,
    createdAt: new Date('2024-06-01').toISOString(),
  },
];

export const DEMO_PRODUCTS = [
  {
    id: '1',
    name: 'iPhone 15 Pro Max 256GB',
    category: 'Elektronika',
    description: 'Eng so\'nggi Apple smartfoni - A17 Pro chip, titanium frame, USB-C',
    price: '18500000',
    costPrice: '16000000',
    sku: 'IP15PM-256-BLK',
    barcode: '190199123456',
    weight: '221',
    stock: 45,
    isActive: true,
    aiGenerated: true,
    marketplace: 'Uzum',
    views: 12500,
    orders: 89,
    rating: 4.9,
    createdAt: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'Samsung Galaxy S24 Ultra 512GB',
    category: 'Elektronika',
    description: 'Premium Android smartfon - Snapdragon 8 Gen 3, S Pen, AI Features',
    price: '16500000',
    costPrice: '14000000',
    sku: 'SGS24U-512-GRN',
    barcode: '887276654321',
    weight: '233',
    stock: 32,
    isActive: true,
    aiGenerated: true,
    marketplace: 'Wildberries',
    views: 9800,
    orders: 67,
    rating: 4.8,
    createdAt: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'MacBook Air M3 15" 512GB',
    category: 'Kompyuter',
    description: 'Yengil va kuchli noutbuk - M3 chip, 18 soat batareya, Retina display',
    price: '22000000',
    costPrice: '19000000',
    sku: 'MBA-M3-15-512',
    barcode: '194253456789',
    weight: '1510',
    stock: 18,
    isActive: true,
    aiGenerated: true,
    marketplace: 'Uzum',
    views: 6700,
    orders: 34,
    rating: 4.9,
    createdAt: new Date().toISOString(),
  },
  {
    id: '4',
    name: 'AirPods Pro 2nd Gen',
    category: 'Aksessuar',
    description: 'Premium simsiz quloqchinlar - ANC, Adaptive Audio, USB-C',
    price: '3200000',
    costPrice: '2600000',
    sku: 'APP2-USBC',
    barcode: '194253789012',
    weight: '51',
    stock: 120,
    isActive: true,
    aiGenerated: true,
    marketplace: 'Ozon',
    views: 15200,
    orders: 156,
    rating: 4.7,
    createdAt: new Date().toISOString(),
  },
  {
    id: '5',
    name: 'iPad Pro M4 12.9" 256GB',
    category: 'Planshet',
    description: 'Eng kuchli planshet - M4 chip, OLED display, Thunderbolt',
    price: '19500000',
    costPrice: '17000000',
    sku: 'IPADP-M4-129-256',
    barcode: '194253567890',
    weight: '682',
    stock: 22,
    isActive: true,
    aiGenerated: false,
    marketplace: 'Uzum',
    views: 4300,
    orders: 21,
    rating: 4.9,
    createdAt: new Date().toISOString(),
  },
];

export const DEMO_ORDERS = [
  {
    id: 'ORD-001',
    productId: '1',
    productName: 'iPhone 15 Pro Max 256GB',
    quantity: 1,
    price: '18500000',
    status: 'delivered',
    marketplace: 'Uzum',
    customerName: 'Alijon Karimov',
    customerPhone: '+998901234567',
    address: 'Toshkent, Mirzo Ulug\'bek tumani',
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    deliveredAt: new Date().toISOString(),
  },
  {
    id: 'ORD-002',
    productId: '2',
    productName: 'Samsung Galaxy S24 Ultra',
    quantity: 2,
    price: '33000000',
    status: 'shipped',
    marketplace: 'Wildberries',
    customerName: 'Sardor Normatov',
    customerPhone: '+998909876543',
    address: 'Samarqand, Registon ko\'chasi',
    createdAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: 'ORD-003',
    productId: '4',
    productName: 'AirPods Pro 2nd Gen',
    quantity: 3,
    price: '9600000',
    status: 'processing',
    marketplace: 'Ozon',
    customerName: 'Dilshod Azimov',
    customerPhone: '+998905551234',
    address: 'Buxoro, Mustaqillik ko\'chasi',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'ORD-004',
    productId: '3',
    productName: 'MacBook Air M3 15"',
    quantity: 1,
    price: '22000000',
    status: 'pending',
    marketplace: 'Uzum',
    customerName: 'Nodira Saidova',
    customerPhone: '+998901112233',
    address: 'Toshkent, Yunusobod tumani',
    createdAt: new Date().toISOString(),
  },
];

export const DEMO_ANALYTICS = {
  today: {
    revenue: 125000000,
    orders: 47,
    profit: 25000000,
    views: 3450,
    conversion: 1.36,
  },
  yesterday: {
    revenue: 98000000,
    orders: 35,
    profit: 19600000,
    views: 2890,
    conversion: 1.21,
  },
  thisWeek: {
    revenue: 756000000,
    orders: 287,
    profit: 151200000,
    views: 21500,
    conversion: 1.34,
  },
  thisMonth: {
    revenue: 2890000000,
    orders: 1156,
    profit: 578000000,
    views: 87600,
    conversion: 1.32,
  },
  chart: [
    { date: '01.06', revenue: 85000000, orders: 32 },
    { date: '02.06', revenue: 92000000, orders: 38 },
    { date: '03.06', revenue: 78000000, orders: 28 },
    { date: '04.06', revenue: 105000000, orders: 42 },
    { date: '05.06', revenue: 115000000, orders: 48 },
    { date: '06.06', revenue: 98000000, orders: 35 },
    { date: '07.06', revenue: 125000000, orders: 47 },
  ],
  byMarketplace: [
    { name: 'Uzum', revenue: 1450000000, orders: 580, share: 50 },
    { name: 'Wildberries', revenue: 870000000, orders: 350, share: 30 },
    { name: 'Ozon', revenue: 570000000, orders: 226, share: 20 },
  ],
  byCategory: [
    { name: 'Elektronika', revenue: 2023000000, orders: 810 },
    { name: 'Aksessuar', revenue: 578000000, orders: 230 },
    { name: 'Planshet', revenue: 289000000, orders: 116 },
  ],
};

export const DEMO_STATS = {
  totalRevenue: 2890000000,
  totalOrders: 1156,
  totalProfit: 578000000,
  totalProducts: 5,
  activeProducts: 5,
  pendingOrders: 12,
  processingOrders: 28,
  shippedOrders: 45,
  completedOrders: 1071,
  averageOrderValue: 2500000,
  conversionRate: 1.32,
  returnRate: 2.1,
  customerSatisfaction: 4.8,
};

export const DEMO_AI_STATS = {
  cardsGenerated: 1247,
  cardsThisMonth: 156,
  avgGenerationTime: 38,
  successRate: 98.5,
  translationsCompleted: 3741,
  seoOptimizations: 892,
  priceOptimizations: 456,
  totalTimeSaved: 312, // soatda
  tasksQueue: 5,
  tasksCompleted: 1892,
};

export const DEMO_WALLET = {
  balance: 12500000,
  pendingWithdrawal: 0,
  totalEarned: 578000000,
  totalWithdrawn: 565500000,
  commissionPaid: 101150000,
  transactions: [
    { id: 't1', type: 'earning', amount: 2500000, description: 'Kunlik savdo daromadi', date: new Date().toISOString() },
    { id: 't2', type: 'commission', amount: -437500, description: 'Platforma komissiyasi', date: new Date().toISOString() },
    { id: 't3', type: 'withdrawal', amount: -10000000, description: 'Click orqali yechib olindi', date: new Date(Date.now() - 86400000 * 3).toISOString() },
    { id: 't4', type: 'earning', amount: 1960000, description: 'Kunlik savdo daromadi', date: new Date(Date.now() - 86400000).toISOString() },
  ],
};

export const DEMO_NOTIFICATIONS = [
  { id: 'n1', type: 'order', title: 'Yangi buyurtma', message: 'iPhone 15 Pro Max - 1 dona', isRead: false, createdAt: new Date().toISOString() },
  { id: 'n2', type: 'ai', title: 'AI kartochka tayyor', message: 'Samsung Galaxy S24 Ultra uchun kartochka yaratildi', isRead: false, createdAt: new Date(Date.now() - 3600000).toISOString() },
  { id: 'n3', type: 'stock', title: 'Kam qoldi', message: 'MacBook Air M3 - faqat 18 dona qoldi', isRead: true, createdAt: new Date(Date.now() - 7200000).toISOString() },
  { id: 'n4', type: 'payment', title: 'To\'lov qabul qilindi', message: '10,000,000 so\'m muvaffaqiyatli yechib olindi', isRead: true, createdAt: new Date(Date.now() - 86400000).toISOString() },
];

export const DEMO_ADMIN_STATS = {
  totalPartners: 2847,
  activePartners: 2156,
  newPartnersThisMonth: 187,
  partnersGrowth: 12.5,
  totalRevenue: 45700000000,
  revenueThisMonth: 4890000000,
  revenueGrowth: 18.3,
  totalCommission: 1599500000,
  commissionThisMonth: 171150000,
  totalProducts: 127450,
  activeProducts: 98560,
  totalOrders: 892456,
  ordersThisMonth: 78450,
  activeAITasks: 234,
  aiTasksCompleted: 45678,
  aiEfficiency: 98.2,
  connectedMarketplaces: 5,
  activeIntegrations: 3,
  supportTickets: 23,
  resolvedTickets: 890,
  avgResolutionTime: 4.2, // soatda
};

export const DEMO_TIER_REQUESTS = [
  {
    id: 'tr1',
    partnerId: 'partner-3',
    partnerName: 'Home Comfort',
    currentTier: 'basic',
    requestedTier: 'starter_pro',
    reason: 'Savdo hajmi oshdi, ko\'proq mahsulotlar qo\'shmoqchiman',
    status: 'pending',
    createdAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: 'tr2',
    partnerId: 'partner-4',
    partnerName: 'Sport Pro',
    currentTier: 'free_starter',
    requestedTier: 'basic',
    reason: 'Biznes kengaymoqda, AI funksiyalari kerak',
    status: 'pending',
    createdAt: new Date().toISOString(),
  },
];

// Doimiy demo mode - Lovable faqat frontend ishga tushiradi
export function isDemoMode(): boolean {
  return true;
}

export function setDemoMode(enabled: boolean): void {
  // Lovable uchun doimiy true
}

export function getDemoMode(): boolean {
  return true;
}
