// server/services/fulfillmentAIIntegration.ts
// FULFILLMENT → AI MANAGER INTEGRATION

import { db } from '../db';
import { calculateOptimalPrice } from './priceCalculationService';
import { createProductCard } from './aiMarketplaceManager';

interface FulfillmentProduct {
  id: number;
  partner_id: number;
  product_name: string;
  category: string;
  description?: string;
  cost_price: number; // Tannarx
  quantity: number;
  images?: string[];
  fulfillment_request_id: number;
}

/**
 * Fulfillment qabul qilingandan keyin AI Manager'ni ishga tushirish
 * Bu funksiya admin fulfillment'ni "accepted" holatiga o'tkazganda chaqiriladi
 */
export async function triggerAIForFulfillment(
  fulfillmentRequestId: number,
  adminId: string
) {
  console.log('\ud83e\udd16 Starting AI workflow for fulfillment:', fulfillmentRequestId);

  try {
    // 1. Get fulfillment request details
    const fulfillmentRequest = await db.get(
      `SELECT * FROM fulfillment_requests WHERE id = ?`,
      [fulfillmentRequestId]
    );

    if (!fulfillmentRequest) {
      throw new Error(`Fulfillment request ${fulfillmentRequestId} not found`);
    }

    const partnerId = fulfillmentRequest.partner_id;

    // 2. Get partner info and tier (including linked user)
    const partner = await db.get(
      `SELECT * FROM partners WHERE id = ?`,
      [partnerId]
    );

    if (!partner) {
      throw new Error(`Partner ${partnerId} not found`);
    }

    const partnerTier = partner.pricing_tier || 'starter_pro';

    // 3. Get partner's user id (needed for ai_marketplace_accounts)
    const partnerUserId = partner.user_id;

    // 3a. Get AI-enabled marketplace accounts for this user
    const marketplaceAccounts = await db.all(
      `SELECT id, marketplace 
       FROM ai_marketplace_accounts 
       WHERE partner_id = ? AND account_status = 'active' AND ai_enabled = 1`,
      [partnerUserId]
    );

    if (!marketplaceAccounts || marketplaceAccounts.length === 0) {
      console.log('\u26a0\ufe0f No AI-enabled marketplace accounts for user:', partnerUserId);
      return {
        success: false,
        message: 'No active AI marketplace accounts',
        productsProcessed: 0,
      };
    }

    // 4. Get products from fulfillment request
    const products = await db.all(
      `SELECT * FROM fulfillment_request_items WHERE fulfillment_request_id = ?`,
      [fulfillmentRequestId]
    );

    if (products.length === 0) {
      throw new Error('No products in fulfillment request');
    }

    console.log(`\ud83d\udce6 Processing ${products.length} products for ${marketplaceAccounts.length} AI accounts`);

    const results: any[] = [];

    // 5. For each product, create AI-generated cards for all AI-enabled marketplace accounts
    for (const product of products) {
      // Process each marketplace
      for (const account of marketplaceAccounts) {
        const marketplaceType = account.marketplace as any;

        try {
          // Calculate optimal price using our intelligent price calculator
          const priceResult = calculateOptimalPrice({
            costPrice: parseFloat(product.cost_price || '0'),
            productCategory: product.category || 'default',
            marketplaceType,
            partnerTier,
            targetMargin: 0.25, // 25% default profit margin
          });

          console.log(`\ud83d\udcb0 Price calculated for ${product.product_name} on ${marketplaceType}:`, priceResult.recommendedPrice);

          // Generate AI product card using the new Anthropic-based service
          const aiCard = await createProductCard(
            {
              name: product.product_name,
              category: product.category || 'general',
              features: [
                'Autogenerated from fulfillment request',
                `Fulfillment ID: ${fulfillmentRequestId}`,
              ],
              targetAudience: 'Marketplace buyers',
            },
            marketplaceType
          );

          // Store into ai_product_cards (0008 schema)
          await db.run(
            `INSERT INTO ai_product_cards (
               account_id,
               marketplace,
               base_product_name,
               optimized_title,
               optimized_description,
               seo_keywords,
               category,
               attributes,
               price,
               images_data,
               seo_score,
               performance_score,
               status
             ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)` ,
            [
              account.id,
              marketplaceType,
              product.product_name,
              aiCard.title,
              aiCard.description,
              JSON.stringify(aiCard.keywords || []),
              product.category || 'general',
              JSON.stringify({ source: 'fulfillment', fulfillmentRequestId }),
              priceResult.recommendedPrice,
              product.images || '[]',
              aiCard.seoScore || 0,
              aiCard.seoScore || 0,
              'draft',
            ]
          );

          results.push({
            product: product.product_name,
            marketplace: marketplaceType,
            status: 'generated',
            price: priceResult.recommendedPrice,
            seoScore: aiCard.seoScore || 0,
          });
        } catch (error: any) {
          console.error(`\u274c Error processing ${product.product_name} for ${marketplaceType}:`, error.message);
          results.push({
            product: product.product_name,
            marketplace: marketplaceType,
            status: 'error',
            error: error.message,
          });
        }
      }
    }

    // 6. Update fulfillment request with AI processing status
    await db.run(
      `UPDATE fulfillment_requests 
       SET ai_processed = 1,
           ai_processed_at = CURRENT_TIMESTAMP,
           ai_processing_notes = ?
       WHERE id = ?`,
      [JSON.stringify(results), fulfillmentRequestId]
    );

    const successCount = results.filter((r) => r.status === 'generated').length;
    const errorCount = results.filter((r) => r.status === 'error').length;

    console.log(`\u2705 AI workflow completed: ${successCount} success, ${errorCount} errors`);

    return {
      success: true,
      message: `AI processed ${successCount} product cards`,
      productsProcessed: successCount,
      errors: errorCount,
      details: results,
    };
  } catch (error: any) {
    console.error('\u274c AI workflow error:', error.message);
    throw error;
  }
}

/**
 * Manually trigger AI for a specific product
 * Admin can use this to retry failed products
 */
export async function manuallyTriggerAIForProduct(
  productId: number,
  marketplaceType: string,
  adminId: string
) {
  console.log(`\ud83d\udd04 Manually triggering AI for product ${productId} on ${marketplaceType}`);

  try {
    // Get product details from fulfillment_request_items
    const product = await db.get(
      `SELECT * FROM fulfillment_request_items WHERE id = ?`,
      [productId]
    );

    if (!product) {
      throw new Error(`Product ${productId} not found`);
    }

    const partnerId = product.partner_id;

    // Get partner tier and linked user
    const partner = await db.get(
      `SELECT * FROM partners WHERE id = ?`,
      [partnerId]
    );

    if (!partner) {
      throw new Error(`Partner ${partnerId} not found`);
    }

    const partnerTier = partner.pricing_tier || 'starter_pro';
    const partnerUserId = partner.user_id;

    // Find a matching AI-enabled marketplace account for this user + marketplace
    const account = await db.get(
      `SELECT id, marketplace FROM ai_marketplace_accounts 
       WHERE partner_id = ? AND marketplace = ? AND account_status = 'active' AND ai_enabled = 1`,
      [partnerUserId, marketplaceType]
    );

    if (!account) {
      throw new Error(`No active AI marketplace account for ${marketplaceType}`);
    }

    // Calculate price
    const priceResult = calculateOptimalPrice({
      costPrice: parseFloat(product.cost_price || '0'),
      productCategory: product.category || 'default',
      marketplaceType: marketplaceType as any,
      partnerTier,
      targetMargin: 0.25,
    });

    // Generate AI product card using Anthropic-based service
    const aiCard = await createProductCard(
      {
        name: product.product_name,
        category: product.category || 'general',
        features: [
          'Manual trigger from admin',
          `Fulfillment item ID: ${productId}`,
        ],
        targetAudience: 'Marketplace buyers',
      },
      marketplaceType as any
    );

    await db.run(
      `INSERT INTO ai_product_cards (
         account_id,
         marketplace,
         base_product_name,
         optimized_title,
         optimized_description,
         seo_keywords,
         category,
         attributes,
         price,
         images_data,
         seo_score,
         performance_score,
         status
       ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)` ,
      [
        account.id,
        marketplaceType,
        product.product_name,
        aiCard.title,
        aiCard.description,
        JSON.stringify(aiCard.keywords || []),
        product.category || 'general',
        JSON.stringify({ source: 'manual', adminId }),
        priceResult.recommendedPrice,
        product.images || '[]',
        aiCard.seoScore || 0,
        aiCard.seoScore || 0,
        'draft',
      ]
    );

    return {
      success: true,
      message: 'AI product card generated',
      productId,
      data: aiCard,
    };
  } catch (error: any) {
    console.error('\u274c Manual AI trigger error:', error.message);
    throw error;
  }
}

export default {
  triggerAIForFulfillment,
  manuallyTriggerAIForProduct,
};
